config/routes.rb
Rails.application.routes.draw do
  resources :games
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: %i[ show edit update destroy ]

  # GET /games or /games.json
  def index
    @games = Game.all
  end

  # GET /games/1 or /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games or /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to game_url(@game), notice: "Game was successfully created." }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1 or /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to game_url(@game), notice: "Game was successfully updated." }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1 or /games/1.json
  def destroy
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url, notice: "Game was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def game_params
      params.require(:game).permit(:name, :summary, :release_date, :photo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :summary %>
    <%= form.text_area :summary %>
  </div>

  <div class="field">
    <%= form.label :release_date %>
    <%= form.date_select :release_date %>
  </div>

   <div class="field">
    <%= form.label :photo %>
    <%= form.file_field :photo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>
<div class=container-fluid>
  <%= render 'form', game: @game %>
</div>
<div class=container-fluid>
  <div class="btn-group" role="group" aria-label="Basic example" >
   <button type="button" class="btn btn-light"><%= link_to 'Show', @game %> </button>
   <button type="button" class="btn btn-light"><%= link_to 'Back', games_path %></button>
  </div>
</div>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<header class="container-fluid">
  <h1>Games</h1>
  <p class=botongame><button type="button" class="btn btn-light"><%= link_to 'New Game', new_game_path %></button></p>

</header>

<nav>

</nav>

  <div class="container-fluid">
    <table class="table table-dark table-striped-columns">
      <thead>
        <tr>
          <th>Name</th>
          <th>Image</th>
          <th>Summary</th>
          <th>Release date</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @games.each do |game| %>
          <tr>
            <td><%= game.name %></td>
            <td><%= image_tag game.photo if game.photo.attached? %></td>
            <td><%= game.summary %></td>
            <td><%= game.release_date %></td>
            <td class="bi bi-eye"><%= link_to 'Show', game %></td>
            <td class="bi bi-pencil"><%= link_to 'Edit', edit_game_path(game) %></td>
            <td class="bi bi-trash"><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<br>

app/views/games/new.html.erb
<h1>New Game</h1>
<div class=container-fluid>
  <%= render 'form', game: @game %>
</div>
<div class=container-fluid>
<button type="button" class="btn btn-light"><%= link_to 'Back', games_path %></button>
</div>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>
<div class=container-fluid>
  <p>
    <strong>Name:</strong>
    <%= @game.name %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= @game.image %>
    <%= image_tag @game.photo if @game.photo.attached? %>
  </p>

  <p>
    <strong>Summary:</strong>
    <%= @game.summary %>
  </p>

  <p>
    <strong>Release date:</strong>
    <%= @game.release_date %>
  </p>
</div>
<div class=container-fluid>
  <div class="btn-group" role="group" aria-label="Basic example">
    <button type="button" class="btn btn-light"><%= link_to 'Edit', edit_game_path(@game) %> </button>
    <button type="button" class="btn btn-light"><%= link_to 'Back', games_path %></button>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gameproject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
  </head>

  <body>
    <header class=header>
      <h1 class=titulo>Explorer Game </h1>
    </header>
    <div class=container-fluid>
    <p class=descripcion>Bienvenidos a Explorer Game, el lugar donde podrás encontrar y añadir detalles de tus juegos favoritos, en este lugar iremos añadiendo detalles de todo tipo para generar una base de datos completa de juegos de todo tipo y para todas las consolas.</p>
    </div>
    <%= yield %>
  </body>
</html>